
namespace file_utils {
    enum FileType {
        f_unknown = 0,
        f_jpg,
        f_png,
        f_gif,
        f_webp,
        f_cr2,
        f_tif,
        f_bmp,
        f_jxr,
        f_psd,
        f_epub,
        f_xpi,
        f_zip,
        f_tar,
        f_rar,
        f_gz,
        f_bz2,
        f_7z,
        f_dmg,
        f_mp4,
        f_m4v,
        f_mid,
        f_mkv,
        f_webm,
        f_mov,
        f_avi,
        f_wmv,
        f_mpg,
        f_mp3,
        f_m4a,
        f_opus,
        f_ogg,
        f_flac,
        f_wav,
        f_amr,
        f_pdf,
        f_exe,
        f_swf,
        f_rtf,
        f_woff,
        f_woff2,
        f_eot,
        f_ttf,
        f_otf,
        f_ico,
        f_flv,
        f_ps,
        f_xz,
        f_sqlite,
        f_nes,
        f_crx,
        f_cab,
        f_deb,
        f_ar,
        f_rpm,
        f_Z,
        f_lz,
        f_msi
    };
}

#include <string>
#include <map>

extern std::map<std::string, file_utils::FileType> Map = 
{
    {"jpg", file_utils::FileType::f_jpg},
    {"png", file_utils::FileType::f_png},
    {"gif", file_utils::FileType::f_gif},
    {"webp", file_utils::FileType::f_webp},
    {"cr2", file_utils::FileType::f_cr2},
    {"tif", file_utils::FileType::f_tif},
    {"bmp", file_utils::FileType::f_bmp},
    {"jxr", file_utils::FileType::f_jxr},
    {"psd", file_utils::FileType::f_psd},
    {"epub", file_utils::FileType::f_epub},
    {"xpi", file_utils::FileType::f_xpi},
    {"zip", file_utils::FileType::f_zip},
    {"tar", file_utils::FileType::f_tar},
    {"rar", file_utils::FileType::f_rar},
    {"gz", file_utils::FileType::f_gz},
    {"bz2", file_utils::FileType::f_bz2},
    {"7z", file_utils::FileType::f_7z},
    {"dmg", file_utils::FileType::f_dmg},
    {"mp4", file_utils::FileType::f_mp4},
    {"m4v", file_utils::FileType::f_m4v},
    {"mid", file_utils::FileType::f_mid},
    {"mkv", file_utils::FileType::f_mkv},
    {"webm", file_utils::FileType::f_webm},
    {"mov", file_utils::FileType::f_mov},
    {"avi", file_utils::FileType::f_avi},
    {"wmv", file_utils::FileType::f_wmv},
    {"mpg", file_utils::FileType::f_mpg},
    {"mp3", file_utils::FileType::f_mp3},
    {"m4a", file_utils::FileType::f_m4a},
    {"opus", file_utils::FileType::f_opus},
    {"ogg", file_utils::FileType::f_ogg},
    {"flac", file_utils::FileType::f_flac},
    {"wav", file_utils::FileType::f_wav},
    {"amr", file_utils::FileType::f_amr},
    {"pdf", file_utils::FileType::f_pdf},
    {"exe", file_utils::FileType::f_exe},
    {"swf", file_utils::FileType::f_swf},
    {"rtf", file_utils::FileType::f_rtf},
    {"woff", file_utils::FileType::f_woff},
    {"woff2", file_utils::FileType::f_woff2},
    {"eot", file_utils::FileType::f_eot},
    {"ttf", file_utils::FileType::f_ttf},
    {"otf", file_utils::FileType::f_otf},
    {"ico", file_utils::FileType::f_ico},
    {"flv", file_utils::FileType::f_flv},
    {"ps", file_utils::FileType::f_ps},
    {"xz", file_utils::FileType::f_xz},
    {"sqlite", file_utils::FileType::f_sqlite},
    {"nes", file_utils::FileType::f_nes},
    {"crx", file_utils::FileType::f_crx},
    {"cab", file_utils::FileType::f_cab},
    {"deb", file_utils::FileType::f_deb},
    {"ar", file_utils::FileType::f_ar},
    {"rpm", file_utils::FileType::f_rpm},
    {"Z", file_utils::FileType::f_Z},
    {"lz", file_utils::FileType::f_lz},
    {"msi", file_utils::FileType::f_msi},
};

