
namespace f_type {
    enum FileType {
        f_unknown = 0,
        f_jpg,
        f_png,
        f_gif,
        f_webp,
        f_cr2,
        f_tif,
        f_bmp,
        f_jxr,
        f_psd,
        f_epub,
        f_xpi,
        f_zip,
        f_tar,
        f_rar,
        f_gz,
        f_bz2,
        f_7z,
        f_dmg,
        f_mp4,
        f_m4v,
        f_mid,
        f_mkv,
        f_webm,
        f_mov,
        f_avi,
        f_wmv,
        f_mpg,
        f_mp3,
        f_m4a,
        f_opus,
        f_ogg,
        f_flac,
        f_wav,
        f_amr,
        f_pdf,
        f_exe,
        f_swf,
        f_rtf,
        f_woff,
        f_woff2,
        f_eot,
        f_ttf,
        f_otf,
        f_ico,
        f_flv,
        f_ps,
        f_xz,
        f_sqlite,
        f_nes,
        f_crx,
        f_cab,
        f_deb,
        f_ar,
        f_rpm,
        f_Z,
        f_lz,
        f_msi
    };
}

#include <string>
#include <map>

extern std::map<std::string, f_type::FileType> Map = 
{
    {"jpg", f_type::FileType::f_jpg},
    {"png", f_type::FileType::f_png},
    {"gif", f_type::FileType::f_gif},
    {"webp", f_type::FileType::f_webp},
    {"cr2", f_type::FileType::f_cr2},
    {"tif", f_type::FileType::f_tif},
    {"bmp", f_type::FileType::f_bmp},
    {"jxr", f_type::FileType::f_jxr},
    {"psd", f_type::FileType::f_psd},
    {"epub", f_type::FileType::f_epub},
    {"xpi", f_type::FileType::f_xpi},
    {"zip", f_type::FileType::f_zip},
    {"tar", f_type::FileType::f_tar},
    {"rar", f_type::FileType::f_rar},
    {"gz", f_type::FileType::f_gz},
    {"bz2", f_type::FileType::f_bz2},
    {"7z", f_type::FileType::f_7z},
    {"dmg", f_type::FileType::f_dmg},
    {"mp4", f_type::FileType::f_mp4},
    {"m4v", f_type::FileType::f_m4v},
    {"mid", f_type::FileType::f_mid},
    {"mkv", f_type::FileType::f_mkv},
    {"webm", f_type::FileType::f_webm},
    {"mov", f_type::FileType::f_mov},
    {"avi", f_type::FileType::f_avi},
    {"wmv", f_type::FileType::f_wmv},
    {"mpg", f_type::FileType::f_mpg},
    {"mp3", f_type::FileType::f_mp3},
    {"m4a", f_type::FileType::f_m4a},
    {"opus", f_type::FileType::f_opus},
    {"ogg", f_type::FileType::f_ogg},
    {"flac", f_type::FileType::f_flac},
    {"wav", f_type::FileType::f_wav},
    {"amr", f_type::FileType::f_amr},
    {"pdf", f_type::FileType::f_pdf},
    {"exe", f_type::FileType::f_exe},
    {"swf", f_type::FileType::f_swf},
    {"rtf", f_type::FileType::f_rtf},
    {"woff", f_type::FileType::f_woff},
    {"woff2", f_type::FileType::f_woff2},
    {"eot", f_type::FileType::f_eot},
    {"ttf", f_type::FileType::f_ttf},
    {"otf", f_type::FileType::f_otf},
    {"ico", f_type::FileType::f_ico},
    {"flv", f_type::FileType::f_flv},
    {"ps", f_type::FileType::f_ps},
    {"xz", f_type::FileType::f_xz},
    {"sqlite", f_type::FileType::f_sqlite},
    {"nes", f_type::FileType::f_nes},
    {"crx", f_type::FileType::f_crx},
    {"cab", f_type::FileType::f_cab},
    {"deb", f_type::FileType::f_deb},
    {"ar", f_type::FileType::f_ar},
    {"rpm", f_type::FileType::f_rpm},
    {"Z", f_type::FileType::f_Z},
    {"lz", f_type::FileType::f_lz},
    {"msi", f_type::FileType::f_msi},
};

